# Development environment, customizable configuration
data:
  point:
    sava:
      influxdb:
        enable: false
      opentsdb:
        enable: false
        host: dc3-opentsdb
        port: 4242
      elasticsearch:
        enable: false
        host: dc3-elasticsearch
        port: 9200

eureka:
  instance:
    # Custom node registration IP
    ip-address: ${SERVICE_HOST:192.168.1.3}

spring:
  datasource:
    # Customize MySQL configuration
    url: jdbc:mysql://${MYSQL_HOST:dc3-mysql}:${MYSQL_PORT:3306}/dc3?allowPublicKeyRetrieval=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
  redis:
    # Customize Redis configuration
    host: ${REDIS_HOST:dc3-redis}
    port: ${REDIS_PORT:6379}
  data:
    mongodb:
      # Customize Mongo configuration
      host: ${MONGO_HOST:dc3-mongo}
      port: ${MONGO_PORT:27017}
  cache:
    redis:
      # Customize Cache configuration
      time-to-live: ${CACHE_REDIS_TIME_TO_LIVE:5M}
