driver:
  tenant: 益莲科技
  name: MqttDriver
  type: driver
  project: @project.artifactId@
  description: @project.description@
  schedule:
    status:
      enable: true
      corn: '0/10 * * * * ?'
    read:
      enable: false
      corn: '0/30 * * * * ?'
    custom:
      enable: true
      corn:  '0/5 * * * * ?'
  point-attribute:
    - displayName: 指令Topic
      name: commandTopic
      type: string
      value: commandTopic
      description: 测点/设备接收下行指令的Mqtt主题
      option:
        type: input\select\checkox\switch\time...
        required: true
        data-type: static/url
        data: jsonString
    - displayName: 指令Qos
      name: commandQos
      type: int
      value: 2
      description: 测点/设备接收下行指令的Mqtt主题的Qos
      option:
        type: input\select\checkox\switch\time...
        required: true
        data-type: static/url
        data: jsonString
  mqtt:
    url: ssl://dc3-emqx:8883
    auth-type: X509
    username: dc3
    password: dc3
    ca-crt: classpath:/certs/ca.crt
    client-key-pass: dc3-client
    client-key: classpath:/certs/client.key
    client-crt: classpath:/certs/client.crt
    client:  ${spring.application.name}
    receive-topics:
      - qos: 1
        name: driver/${spring.application.name}/device/+
      - qos: 1
        name: driver/${spring.application.name}/gateway/+
    default-send-topic:
      qos: 1
      name: default/${spring.application.name}
    keep-alive: 15
    completion-timeout: 3000
    batch:
      speed: ${MQTT_BATCH_SPEED:100}
      interval: ${MQTT_BATCH_INTERVAL:5}

server:
  port: 48701
  thread:
    prefix: dc3-thread-
    core-pool-size: 4
    maximum-pool-size: 32
    keep-alive-time: 15

xxl:
  job:
    executor:
      appname: ${driver.project} #${spring.application.name} # 执行器 AppName
      logpath: ${user.home}/logs/xxl-job/${spring.application.name} # 执行器运行日志文件存储磁盘路径
    accessToken: default_token # 执行器通讯TOKEN
    admin:
      addresses: http://127.0.0.1:9090/xxl-job-admin # 调度中心部署跟地址



spring:
  application:
    name: ${driver.project}_${driver.tenant}
  profiles:
    active: local
  cloud:
    # Spring Cloud Stream 配置项，对应 BindingServiceProperties 类
    stream:
      bindings:
        driver-output-01:
          destination: DRIVER-TOPIC-01
        driver-config-input-01:
          destination: DRIVER-CONFIG-TOPIC-01
          group: driver-config-consumer-DRIVER-CONFIG-TOPIC-01

      # Spring Cloud Stream RocketMQ 配置项
      rocketmq:
        # RocketMQ Binder 配置项，对应 RocketMQBinderConfigurationProperties 类
        binder:
          name-server: 192.168.1.2:9876 # RocketMQ Namesrv 地址
        default:
          producer:
            group: driver-producer-group
          consumer:
            orderly: true
            broadcasting: false

    # Spring Cloud Bus 配置项，对应 BusProperties 类
    bus:
      enabled: true # 是否开启，默认为 true
      id: ${spring.application.name}:${server.port} # 编号，Spring Cloud Alibaba 建议使用“应用:端口”的格式
      destination: springCloudBus # 目标消息队列，默认为 springCloudBus



logging:
  file:
    name: ${user.home}/logs/${spring.application.name}.log # 日志文件名，全路径