# Development environment, customizable configuration
eureka:
  instance:
    # Custom node registration IP
    ip-address: ${SERVICE_HOST:192.168.1.3}

# Log config
logging:
  level:
    com.dc3: DEBUG
    com.dc3.common.sdk: DEBUG